### ISSUE TITLE
An image of the original lamp firmware

### ISSUE THREAD

**Issue by dmsergeevich63** [fvollmer/xiomi-desk-lamp-open-firmware#3]
Hello!
I want to recreate the yeelight LXV1.7 board for use as a ceiling light control box.
An esp8266 board should come to me soon, but I do not have such a lamp and therefore I would be very happy if you upload the yeelight firmware image.

**Comment by fvollmer** [comment]
So you mean the original firmware image of this lamp? I could provide the flash backup of my lamp, but I see several problems:
 * The flash image contains personal data like wifi credentials
 * The flash image may contain some kind of token that is unique to the lamp. I actually think this is very likely.
 * I don't have the license to distribute the firmware image

Why do you even want to use a proprietary firmware for your project? In case of any problem you won't have a good way to debug any problems.

**Comment by dmsergeevich63** [comment]
Yes, I mean the original firmware supplied by the lamp manufacturer.
Wi-Fi credentials are not my goal, I am very far away from you and will never be able to use them. You can change the password from your wifi in order to avoid entering with a password that will be in the firmware or make a new copy of the firmware with wifi data or in a state when the lamp is not attached to wifi. Probably for this you will have to reflash your lamp, which certainly requires time and effort. To reduce distribution, you can not spread the image of the firmware in the public domain, and distribute by mail.
Probably the lamp has some kind of unique identifier, but the attempt is not torture, I do not hope that everything will work just like that .. I chose Xiaomi firmware, because the company is constantly evolving and in the future will give the opportunity to conveniently manage them with inexpensive devices, for example o'clock
All controls will be located within walking distance, so changing the firmware or device will not be a problem.

**Comment by fvollmer** [comment]
I'm sorry, but I won't distribute the original firmware. However, good luck with your project!

**Comment by fvollmer** [comment]
Let me share some more thoughts on your idea. If I understood correctly you want to use this firmware to integrate your device into the xiaomi app. Let's assume there is a unique key/token per device. Then I would expect that only devices with a valid key can connect to the xiaomi cloud/app and that every key identifies exactly one device. This would mean you would need a new valid key for each of your custom devices (and you would have to buy a lot of devices to dump the keys).

Why do I think that there is such a key?
 * There is evidence of such a key for the xiaomi vacuum (https://github.com/dgiese/dustcloud/issues/178)
 * It would be reasonable to only allow official licensed products to use the xiaomi cloud

**Comment by dmsergeevich63** [comment]
The token changes every time the device is reset or unbound from the account. https://4pda.ru/forum/index.php?showtopic=881982&st=1280#entry72101797 In any case, this would be the next stage.
What firmware are you using? Are you afraid that I will break your MiHome lamp?

**Comment by fvollmer** [comment]
I don't need to justify myself for not sharing the image of my lamp. The lamp is rather inexpensive and you can just backup the flash yourself.
This is just a small project, which I did for fun. I don't want to spend time debating whether it is a good or a bad idea to share the original firmware. Neither you nor me know for sure what will happen if we just clone the flash backup to multiple devices and try to use them with the xiaomi cloud. It wouldn't be unreasonable to assume that multiple devices with the same id/key (or whatever) might cause some problems.
Your project sounds interesting and I'm very curious to hear about coupling custom devices with the xiaomi cloud/app. I wish you good luck and hope your project is easier than I'm imaging.
