### ISSUE TITLE
Is the WiFi turned off completely?

### ISSUE THREAD

**Issue by puleddu** [fvollmer/xiomi-desk-lamp-open-firmware#4]
When this (or a similar) firmware is applied, does it meant the WiFi module is turned off and there will be no RF emissions? Or is it just not successfully establishing a connection, but still being "on"? 

I have no knowledge whatsoever in this field. But I am curious about the potential behaviour.

**Comment by fvollmer** [comment]
The lamp is controlled by the ESP8266, which has integrated WiFi support. This micro controller controls the lamp, but the firmware in this repository never enables the WiFi support. Therefor there isn't any RF from the WiFi part.

I'm not sure what you want to archive, but there are two switch mode power supplies for the LEDs, that radiate small amounts of RF (like in nearly every power supply).

**Comment by puleddu** [comment]
Again, I'm only starting to get into getting to know the ESP8266 and I stumbled upon this question on the Arduino StackExchange website: https://arduino.stackexchange.com/questions/43376/can-the-wifi-on-esp8266-be-disabled

My takeaway is that the WiFi needs to be turned off explicitly. Reading your code, I couldn't find any reference to functions or instruction related to that, hence my question. 

Is there a reason why it's not needed in this case? Does it have anything to do with the Arduino way of doing things? Any hint on the direction I should look into, in order to understand this better would be appreciated.
