### ISSUE TITLE
Does this fw disable the Wifi radio?

### ISSUE THREAD

**Issue by bibicu123** [fvollmer/xiomi-desk-lamp-open-firmware#5]
Thank you for the work on firmware.

I just want to disable Wifi radio permanently b/c I am concerned staying with wifi on all night long near my bed.

It isn't clear to me what this firmware does?

Does this firmware disable the wifi radio, or just do not communicate with xiaomi servers?

Is there something that can be desoldered on the PCB to disable wifi permanently?

Also can you put a link to the cable that you used to connect to the lamp, USB to serial.

Thank you again !

**Comment by fvollmer** [comment]
Hi,

this seems to be a reoccuring question. According to the Espressif SDK we would have to enable Wifi via `esp_wifi_init`. This firmware is never initializing the wifi. 
This is different to the modules which ship preloaded with a firmware. These usually automatically initialize the wifi and wait for some AT commands.

Disabling the wifi via Hardware modification would be pretty invasive. You could replace the entire ESP module with another µC of your choice. Another option could be to cut the WiFi Antenna, but I'm not sure if this will completly block wifi access. Cutting the antenna should at least dampen the signal significantly.

I'm not sure what cable I exactly used, but every 3.3V serial cable should work. If you want a nice one you could buy e.g. https://www.digikey.de/product-detail/de/ftdi/TTL-234X-3V3/768-1319-ND/6823715, but a cheap one https://www.ebay.com/itm/USB-to-TTL-Converter-UART-module-CH340G-3-3V-5V-Replace-Pl2303-CP2102/263540409685 will probably work as well (I have no affiliation with neither digikey or the ebay seller).
