### ISSUE TITLE
Backup firmware?

### ISSUE THREAD

**Issue by Sergey-SRG** [fvollmer/xiomi-desk-lamp-open-firmware#6]
Hi , do you have original firmware?

**Comment by fvollmer** [comment]
I made a backup of my lamp. This backup also contains wifi credentials and other personal stuff. You can find some more details on how to dump the firmware in the README.

I can't share my backup, because of copyright reasons.

**Comment by fvollmer** [comment]
There also was a discussion about sharing a firmware image in #3
